[package]
name = "rust-security"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.27", default-features = false, features = [
  "process",
  "user",
] }
argon2 = "0.5"
rand_core = { version = "0.6", features = ["std"] }
